// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Click() {
  return window['go']['main']['App']['Click']();
}

export function CycleDivisionMode() {
  return window['go']['main']['App']['CycleDivisionMode']();
}

export function GetDivisionMode() {
  return window['go']['main']['App']['GetDivisionMode']();
}

export function GetRoundState() {
  return window['go']['main']['App']['GetRoundState']();
}

export function GetTimings() {
  return window['go']['main']['App']['GetTimings']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function ToggleRounding() {
  return window['go']['main']['App']['ToggleRounding']();
}
