// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function Click():Promise<number>;

export function CycleDivisionMode():Promise<void>;

export function GetDivisionMode():Promise<main.DivisionMode>;

export function GetRoundState():Promise<boolean>;

export function GetTimings():Promise<main.Timing>;

export function OpenURL(arg1:string):Promise<void>;

export function Reset():Promise<void>;

export function ToggleRounding():Promise<void>;
